@startuml
!theme bluegray

rectangle "Docker Image / Virtual machine" #D7BDE2 {

    rectangle "Operating System packages" #F9E79F {

        rectangle "Runtime" #A9DFBF {
                rectangle "Application" #D4E6F1 {
                        rectangle "Application dependencies" #F5CBA7 {
                        }
                }
        }
    }
}


@enduml
