@startuml
!theme bluegray

rectangle "Docker Image / Virtual machine" as vm #D7BDE2 {
    note as Nvm
        node, eclipse-temurin
    end note

    rectangle "Operating System packages" as os #F9E79F {
        note as Nos
            openssl, bash, vi
        end note

        rectangle "Runtime" as runtime #A9DFBF {
                note as Nruntime
                    Node.js, JVM
                end note

                rectangle "Application" as app #D4E6F1 {
                        note as Napp
                            Build artifact .jar
                        end note

                        rectangle "Application dependencies" as deps #F5CBA7 {
                                note as Ndeps
                                    Spring Boot, Log4j
                                end note
                        }
                }
        }
    }
}

Nvm -[hidden]d-> os
Nos -[hidden]d-> runtime
Nruntime -[hidden]d-> app
Napp -[hidden]d-> deps

@enduml
