@startuml
!theme bluegray
!pragma layout smetana
skinparam backgroundColor transparent

rectangle "Docker Image / Virtual machine\n<size:11><i>node, eclipse-temurin</i></size>" as vm #D7BDE2 {
    rectangle "OS packages & runtime\n<size:11><i>openssl, bash, vi, Node.js, JVM</i></size>" as os #F9E79F {
        rectangle "Application\n<size:11><i>Build artifact jar file</i></size>" as app #D4E6F1 {
            rectangle "Application dependencies\n<size:11><i>Spring Boot, Log4j</i></size>" as deps #F5CBA7 {
            }
        }
    }
}

@enduml
