@startuml
!theme bluegray
!pragma layout smetana
skinparam backgroundColor transparent

rectangle "Docker Image / Virtual machine" #D7BDE2 {
    rectangle "OS packages & runtime" #F9E79F {
        rectangle "Application" #D4E6F1 {
            rectangle "Application dependencies" #F5CBA7 {
            }
        }
    }
}


@enduml
