@startuml
!theme bluegray
!pragma layout smetana
skinparam backgroundColor transparent
skinparam roundCorner 12
skinparam rectangle {
    BorderColor #586e75
    FontStyle bold
}

rectangle "Docker Image / Virtual machine" #ECE8F7 {
    rectangle "OS packages / Runtime" #FDEBD9 {
        rectangle "Application" #DCEEFB {
            rectangle "Application dependencies" #E6F4D9 {
            }
        }
    }
}

@enduml
