FROM maven:3-eclipse-temurin-17 AS build
WORKDIR /build
COPY pom.xml .
COPY src src
RUN mvn package -DskipTests -q

FROM eclipse-temurin:17-jdk
WORKDIR /app
COPY --from=build /build/target/benchmarks.jar benchmarks.jar
ENTRYPOINT ["java", "-jar", "benchmarks.jar", "-rf", "json", "-rff", "/results/results.json"]

